### ISSUE TITLE
FE open data. Difference between research vs institutional data?

### ISSUE THREAD

**Issue by drchriscole** [watty62/SOD#4]
Just wondering. Is the purpose of this to identify institutional data; as in operational information and/or research data? If either or both it may be worthwhile to split them up as they serve very different purposes.

**Comment by watty62** [comment]
While both have value, in the main I was looking for operational data. 

Splitting research data off into a separate list would be useful. 

Thanks

Ian

**Comment by watty62** [comment]
Closed
